version: "3.9"
services:
  prometheus-client:
    build: ./client
    hostname: einav-prometheus-client
    ports:
    - "8000:8000"
  prometheus:
    build: ./server
    hostname: einav-prometheus
    ports:
      - "9090:9090"
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"