version: "3.9"
services:
  prometheus-client:
    build: .
    hostname: einav-prometheus-client
    ports:
    - "8000:8000"
  prometheus:
    image: "prom/prometheus"
    hostname: einav-prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/i515295/ebay/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"