global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: einav-job
    static_configs:
      - targets: ['einav-prometheus-client:8000']