apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: "{{.Values.nameSpace}}"
spec:
  type: NodePort
  ports:
    - name: "grafana-service"
      port: {{.Values.grafanaPort}}
      targetPort: {{.Values.grafanaPort}}
  selector:
    app: grafana
