apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.prometheusHostName}}"
  namespace: "{{.Values.nameSpace}}"
spec:
  type: NodePort
  ports:
    - port: {{.Values.prometheusPort}}
      targetPort: {{.Values.prometheusPort}}
  selector:
    app: prometheus

