apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.prometheusClientHostName}}"
  namespace: "{{.Values.nameSpace}}"
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.prometheusClientPort}}
      targetPort: {{.Values.prometheusClientPort}}
  selector:
    app: prometheus-client

